

export const BINDINDPHONE_ACTION = 'BINDINDPHONE_ACTION';
export type BINDINDPHONE_ACTION = typeof BINDINDPHONE_ACTION;

export const FINDEMPLOEEBYID_ACTION = 'FINDEMPLOEEBYID_ACTION';
export type FINDEMPLOEEBYID_ACTION = typeof FINDEMPLOEEBYID_ACTION;

export const FINDORGANIZATIONBYIDORNO_ACTION = 'FINDORGANIZATIONBYIDORNO_ACTION';
export type FINDORGANIZATIONBYIDORNO_ACTION = typeof FINDORGANIZATIONBYIDORNO_ACTION;

export const UPDATEEMPLOYEE_ACTION = 'UPDATEEMPLOYEE_ACTION';
export type UPDATEEMPLOYEE_ACTION = typeof UPDATEEMPLOYEE_ACTION;

export const SIGN_ACTION = 'SIGN_ACTION';
export type SIGN_ACTION = typeof SIGN_ACTION;

export const LOGINBYWECHATUSER_ACTION = 'LOGINBYWECHATUSER_ACTION';
export type LOGINBYWECHATUSER_ACTION = typeof LOGINBYWECHATUSER_ACTION;

export const GOTOURL_ACTION = 'GOTOURL_ACTION';
export type GOTOURL_ACTION = typeof GOTOURL_ACTION;

export enum RoleType {
    Clerk = 1,
    Member = 2,
    Shopowner = 4
}

export enum StoreStatuType {
    Normol = 0
}

export enum ClerkStatuType {
    NonActive =0,
    Normol = 1,
    Frozen = 2,
    Deny = 3
}

export const ACCOUNT_TYPE = 'APPLET_MARKTCNTER'