export const USER_ACTION = 'USER_ACTION';
export type USER_ACTION = typeof USER_ACTION;

export const BINDINDPHONE_ACTION = 'BINDINDPHONE_ACTION';
export type BINDINDPHONE_ACTION = typeof BINDINDPHONE_ACTION;
